[package]
name = "team-4"
version = "0.1.0"
edition = "2024"

[dependencies]
tabled = "0.20.0"
clap = { version = "4.5.54", features = ["derive"] }
tokio = { version = "1.49.0", features = ["full"] }
